INSERT INTO linea_editorial VALUES(1,'Administración y gerencia','');
INSERT INTO linea_editorial VALUES(2,'Arquitectura y diseño','');
INSERT INTO linea_editorial VALUES(3,'Arte','');
INSERT INTO linea_editorial VALUES(4,'Artesanía y Manualidades','');
INSERT INTO linea_editorial VALUES(5,'Astrología, metafísica y espiritualidad','');
INSERT INTO linea_editorial VALUES(6,'Auto-ayuda y superación','');
INSERT INTO linea_editorial VALUES(7,'Best-Sellers','');
INSERT INTO linea_editorial VALUES(8,'Ciencia y Tecnología','');
INSERT INTO linea_editorial VALUES(9,'Ciencias Sociales y Comunicación','');
INSERT INTO linea_editorial VALUES(10,'Cine y fotografía','');
INSERT INTO linea_editorial VALUES(11,'Cocina, alimentación, salud','');
INSERT INTO linea_editorial VALUES(12,'Computación e informática','');
INSERT INTO linea_editorial VALUES(13,'Deporte y recreación','');
INSERT INTO linea_editorial VALUES(14,'Derecho','');
INSERT INTO linea_editorial VALUES(15,'Diccionarios, enciclopedias, atlas','');
INSERT INTO linea_editorial VALUES(16,'Economía','');
INSERT INTO linea_editorial VALUES(17,'Educación y pedagogía','');
INSERT INTO linea_editorial VALUES(18,'Filosofía','');
INSERT INTO linea_editorial VALUES(19,'Historia y geografía','');
INSERT INTO linea_editorial VALUES(20,'Humanidades','');
INSERT INTO linea_editorial VALUES(21,'Humor y comics','');
INSERT INTO linea_editorial VALUES(22,'Idiomas','');
INSERT INTO linea_editorial VALUES(23,'Infantiles','');
INSERT INTO linea_editorial VALUES(24,'Literatura','');
INSERT INTO linea_editorial VALUES(25,'Medicina','');
INSERT INTO linea_editorial VALUES(26,'Música y folklore','');
INSERT INTO linea_editorial VALUES(27,'Naturaleza, ecología, turismo','');
INSERT INTO linea_editorial VALUES(28,'Política','');
INSERT INTO linea_editorial VALUES(29,'Psicología','');
INSERT INTO linea_editorial VALUES(30,'Religión','');
INSERT INTO linea_editorial VALUES(31,'Técnicos y profesionales','');
INSERT INTO linea_editorial VALUES(32,'Textos educativos','');
INSERT INTO linea_editorial VALUES(33,'Textos Universitarios','');
INSERT INTO linea_editorial VALUES(34,'Otro','');
