<?php


/**
 * Base class that represents a query for the 'usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.2-dev on:
 *
 * Sat Oct  4 21:39:07 2014
 *
 * @method     UsuarioQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     UsuarioQuery orderByNombre($order = Criteria::ASC) Order by the nombre column
 * @method     UsuarioQuery orderByApellido($order = Criteria::ASC) Order by the apellido column
 * @method     UsuarioQuery orderByCedula($order = Criteria::ASC) Order by the cedula column
 * @method     UsuarioQuery orderByIsbn($order = Criteria::ASC) Order by the isbn column
 * @method     UsuarioQuery orderByLogin($order = Criteria::ASC) Order by the login column
 * @method     UsuarioQuery orderByContrasena($order = Criteria::ASC) Order by the contrasena column
 * @method     UsuarioQuery orderBySfGuardUser($order = Criteria::ASC) Order by the sf_guard_user column
 * @method     UsuarioQuery orderBySexo($order = Criteria::ASC) Order by the sexo column
 * @method     UsuarioQuery orderBySfGuardUserGroup($order = Criteria::ASC) Order by the sf_guard_user_group column
 * @method     UsuarioQuery orderByCorreo($order = Criteria::ASC) Order by the correo column
 * @method     UsuarioQuery orderByTelefono($order = Criteria::ASC) Order by the telefono column
 *
 * @method     UsuarioQuery groupById() Group by the id column
 * @method     UsuarioQuery groupByNombre() Group by the nombre column
 * @method     UsuarioQuery groupByApellido() Group by the apellido column
 * @method     UsuarioQuery groupByCedula() Group by the cedula column
 * @method     UsuarioQuery groupByIsbn() Group by the isbn column
 * @method     UsuarioQuery groupByLogin() Group by the login column
 * @method     UsuarioQuery groupByContrasena() Group by the contrasena column
 * @method     UsuarioQuery groupBySfGuardUser() Group by the sf_guard_user column
 * @method     UsuarioQuery groupBySexo() Group by the sexo column
 * @method     UsuarioQuery groupBySfGuardUserGroup() Group by the sf_guard_user_group column
 * @method     UsuarioQuery groupByCorreo() Group by the correo column
 * @method     UsuarioQuery groupByTelefono() Group by the telefono column
 *
 * @method     UsuarioQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     UsuarioQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     UsuarioQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     Usuario findOne(PropelPDO $con = null) Return the first Usuario matching the query
 * @method     Usuario findOneOrCreate(PropelPDO $con = null) Return the first Usuario matching the query, or a new Usuario object populated from the query conditions when no match is found
 *
 * @method     Usuario findOneById(string $id) Return the first Usuario filtered by the id column
 * @method     Usuario findOneByNombre(string $nombre) Return the first Usuario filtered by the nombre column
 * @method     Usuario findOneByApellido(string $apellido) Return the first Usuario filtered by the apellido column
 * @method     Usuario findOneByCedula(string $cedula) Return the first Usuario filtered by the cedula column
 * @method     Usuario findOneByIsbn(string $isbn) Return the first Usuario filtered by the isbn column
 * @method     Usuario findOneByLogin(string $login) Return the first Usuario filtered by the login column
 * @method     Usuario findOneByContrasena(string $contrasena) Return the first Usuario filtered by the contrasena column
 * @method     Usuario findOneBySfGuardUser(int $sf_guard_user) Return the first Usuario filtered by the sf_guard_user column
 * @method     Usuario findOneBySexo(boolean $sexo) Return the first Usuario filtered by the sexo column
 * @method     Usuario findOneBySfGuardUserGroup(int $sf_guard_user_group) Return the first Usuario filtered by the sf_guard_user_group column
 * @method     Usuario findOneByCorreo(string $correo) Return the first Usuario filtered by the correo column
 * @method     Usuario findOneByTelefono(string $telefono) Return the first Usuario filtered by the telefono column
 *
 * @method     array findById(string $id) Return Usuario objects filtered by the id column
 * @method     array findByNombre(string $nombre) Return Usuario objects filtered by the nombre column
 * @method     array findByApellido(string $apellido) Return Usuario objects filtered by the apellido column
 * @method     array findByCedula(string $cedula) Return Usuario objects filtered by the cedula column
 * @method     array findByIsbn(string $isbn) Return Usuario objects filtered by the isbn column
 * @method     array findByLogin(string $login) Return Usuario objects filtered by the login column
 * @method     array findByContrasena(string $contrasena) Return Usuario objects filtered by the contrasena column
 * @method     array findBySfGuardUser(int $sf_guard_user) Return Usuario objects filtered by the sf_guard_user column
 * @method     array findBySexo(boolean $sexo) Return Usuario objects filtered by the sexo column
 * @method     array findBySfGuardUserGroup(int $sf_guard_user_group) Return Usuario objects filtered by the sf_guard_user_group column
 * @method     array findByCorreo(string $correo) Return Usuario objects filtered by the correo column
 * @method     array findByTelefono(string $telefono) Return Usuario objects filtered by the telefono column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseUsuarioQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseUsuarioQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Usuario', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new UsuarioQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    UsuarioQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof UsuarioQuery) {
			return $criteria;
		}
		$query = new UsuarioQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Usuario|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = UsuarioPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(UsuarioPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(UsuarioPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterById(1234); // WHERE id = 1234
	 * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
	 * $query->filterById(array('min' => 12)); // WHERE id > 12
	 * </code>
	 *
	 * @param     mixed $id The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(UsuarioPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the nombre column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterByNombre('fooValue');   // WHERE nombre = 'fooValue'
	 * $query->filterByNombre('%fooValue%'); // WHERE nombre LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $nombre The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterByNombre($nombre = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($nombre)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $nombre)) {
				$nombre = str_replace('*', '%', $nombre);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(UsuarioPeer::NOMBRE, $nombre, $comparison);
	}

	/**
	 * Filter the query on the apellido column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterByApellido('fooValue');   // WHERE apellido = 'fooValue'
	 * $query->filterByApellido('%fooValue%'); // WHERE apellido LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $apellido The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterByApellido($apellido = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($apellido)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $apellido)) {
				$apellido = str_replace('*', '%', $apellido);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(UsuarioPeer::APELLIDO, $apellido, $comparison);
	}

	/**
	 * Filter the query on the cedula column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterByCedula('fooValue');   // WHERE cedula = 'fooValue'
	 * $query->filterByCedula('%fooValue%'); // WHERE cedula LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $cedula The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterByCedula($cedula = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($cedula)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $cedula)) {
				$cedula = str_replace('*', '%', $cedula);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(UsuarioPeer::CEDULA, $cedula, $comparison);
	}

	/**
	 * Filter the query on the isbn column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterByIsbn('fooValue');   // WHERE isbn = 'fooValue'
	 * $query->filterByIsbn('%fooValue%'); // WHERE isbn LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $isbn The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterByIsbn($isbn = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($isbn)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $isbn)) {
				$isbn = str_replace('*', '%', $isbn);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(UsuarioPeer::ISBN, $isbn, $comparison);
	}

	/**
	 * Filter the query on the login column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterByLogin('fooValue');   // WHERE login = 'fooValue'
	 * $query->filterByLogin('%fooValue%'); // WHERE login LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $login The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterByLogin($login = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($login)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $login)) {
				$login = str_replace('*', '%', $login);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(UsuarioPeer::LOGIN, $login, $comparison);
	}

	/**
	 * Filter the query on the contrasena column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterByContrasena('fooValue');   // WHERE contrasena = 'fooValue'
	 * $query->filterByContrasena('%fooValue%'); // WHERE contrasena LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $contrasena The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterByContrasena($contrasena = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($contrasena)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $contrasena)) {
				$contrasena = str_replace('*', '%', $contrasena);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(UsuarioPeer::CONTRASENA, $contrasena, $comparison);
	}

	/**
	 * Filter the query on the sf_guard_user column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterBySfGuardUser(1234); // WHERE sf_guard_user = 1234
	 * $query->filterBySfGuardUser(array(12, 34)); // WHERE sf_guard_user IN (12, 34)
	 * $query->filterBySfGuardUser(array('min' => 12)); // WHERE sf_guard_user > 12
	 * </code>
	 *
	 * @param     mixed $sfGuardUser The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterBySfGuardUser($sfGuardUser = null, $comparison = null)
	{
		if (is_array($sfGuardUser)) {
			$useMinMax = false;
			if (isset($sfGuardUser['min'])) {
				$this->addUsingAlias(UsuarioPeer::SF_GUARD_USER, $sfGuardUser['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($sfGuardUser['max'])) {
				$this->addUsingAlias(UsuarioPeer::SF_GUARD_USER, $sfGuardUser['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(UsuarioPeer::SF_GUARD_USER, $sfGuardUser, $comparison);
	}

	/**
	 * Filter the query on the sexo column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterBySexo(true); // WHERE sexo = true
	 * $query->filterBySexo('yes'); // WHERE sexo = true
	 * </code>
	 *
	 * @param     boolean|string $sexo The value to use as filter.
	 *              Non-boolean arguments are converted using the following rules:
	 *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
	 *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
	 *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterBySexo($sexo = null, $comparison = null)
	{
		if (is_string($sexo)) {
			$sexo = in_array(strtolower($sexo), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
		}
		return $this->addUsingAlias(UsuarioPeer::SEXO, $sexo, $comparison);
	}

	/**
	 * Filter the query on the sf_guard_user_group column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterBySfGuardUserGroup(1234); // WHERE sf_guard_user_group = 1234
	 * $query->filterBySfGuardUserGroup(array(12, 34)); // WHERE sf_guard_user_group IN (12, 34)
	 * $query->filterBySfGuardUserGroup(array('min' => 12)); // WHERE sf_guard_user_group > 12
	 * </code>
	 *
	 * @param     mixed $sfGuardUserGroup The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterBySfGuardUserGroup($sfGuardUserGroup = null, $comparison = null)
	{
		if (is_array($sfGuardUserGroup)) {
			$useMinMax = false;
			if (isset($sfGuardUserGroup['min'])) {
				$this->addUsingAlias(UsuarioPeer::SF_GUARD_USER_GROUP, $sfGuardUserGroup['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($sfGuardUserGroup['max'])) {
				$this->addUsingAlias(UsuarioPeer::SF_GUARD_USER_GROUP, $sfGuardUserGroup['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(UsuarioPeer::SF_GUARD_USER_GROUP, $sfGuardUserGroup, $comparison);
	}

	/**
	 * Filter the query on the correo column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterByCorreo('fooValue');   // WHERE correo = 'fooValue'
	 * $query->filterByCorreo('%fooValue%'); // WHERE correo LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $correo The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterByCorreo($correo = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($correo)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $correo)) {
				$correo = str_replace('*', '%', $correo);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(UsuarioPeer::CORREO, $correo, $comparison);
	}

	/**
	 * Filter the query on the telefono column
	 * 
	 * Example usage:
	 * <code>
	 * $query->filterByTelefono('fooValue');   // WHERE telefono = 'fooValue'
	 * $query->filterByTelefono('%fooValue%'); // WHERE telefono LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $telefono The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function filterByTelefono($telefono = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($telefono)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $telefono)) {
				$telefono = str_replace('*', '%', $telefono);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(UsuarioPeer::TELEFONO, $telefono, $comparison);
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Usuario $usuario Object to remove from the list of results
	 *
	 * @return    UsuarioQuery The current query, for fluid interface
	 */
	public function prune($usuario = null)
	{
		if ($usuario) {
			$this->addUsingAlias(UsuarioPeer::ID, $usuario->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseUsuarioQuery
