<?php


/**
 * Base class that represents a row from the 'pago_expositor' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.2-dev on:
 *
 * Mon May 11 16:29:20 2015
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BasePagoExpositor extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
	const PEER = 'PagoExpositorPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PagoExpositorPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        string
	 */
	protected $id;

	/**
	 * The value for the monto field.
	 * @var        string
	 */
	protected $monto;

	/**
	 * The value for the id_feria field.
	 * @var        int
	 */
	protected $id_feria;

	/**
	 * The value for the id_expositor field.
	 * @var        int
	 */
	protected $id_expositor;

	/**
	 * The value for the id_usuario field.
	 * @var        int
	 */
	protected $id_usuario;

	/**
	 * The value for the id_expositor_feria field.
	 * @var        int
	 */
	protected $id_expositor_feria;

	/**
	 * The value for the status_actual field.
	 * @var        boolean
	 */
	protected $status_actual;

	/**
	 * The value for the pago_aprobado field.
	 * @var        boolean
	 */
	protected $pago_aprobado;

	/**
	 * The value for the fecha field.
	 * Note: this column has a database default value of: (expression) now()
	 * @var        string
	 */
	protected $fecha;

	/**
	 * The value for the id_banco field.
	 * @var        int
	 */
	protected $id_banco;

	/**
	 * The value for the numero_deposito field.
	 * @var        int
	 */
	protected $numero_deposito;

	/**
	 * The value for the fecha_pago field.
	 * @var        string
	 */
	protected $fecha_pago;

	/**
	 * The value for the es_pago_banco_nacional field.
	 * @var        boolean
	 */
	protected $es_pago_banco_nacional;

	/**
	 * @var        Feria
	 */
	protected $aFeria;

	/**
	 * @var        Expositor
	 */
	protected $aExpositor;

	/**
	 * @var        Usuario
	 */
	protected $aUsuario;

	/**
	 * @var        ExpositorFeria
	 */
	protected $aExpositorFeria;

	/**
	 * @var        Banco
	 */
	protected $aBanco;

	/**
	 * @var        array Status[] Collection to store aggregation of Status objects.
	 */
	protected $collStatuss;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Initializes internal state of BasePagoExpositor object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [monto] column value.
	 * 
	 * @return     string
	 */
	public function getMonto()
	{
		return $this->monto;
	}

	/**
	 * Get the [id_feria] column value.
	 * 
	 * @return     int
	 */
	public function getIdFeria()
	{
		return $this->id_feria;
	}

	/**
	 * Get the [id_expositor] column value.
	 * 
	 * @return     int
	 */
	public function getIdExpositor()
	{
		return $this->id_expositor;
	}

	/**
	 * Get the [id_usuario] column value.
	 * 
	 * @return     int
	 */
	public function getIdUsuario()
	{
		return $this->id_usuario;
	}

	/**
	 * Get the [id_expositor_feria] column value.
	 * 
	 * @return     int
	 */
	public function getIdExpositorFeria()
	{
		return $this->id_expositor_feria;
	}

	/**
	 * Get the [status_actual] column value.
	 * 
	 * @return     boolean
	 */
	public function getStatusActual()
	{
		return $this->status_actual;
	}

	/**
	 * Get the [pago_aprobado] column value.
	 * 
	 * @return     boolean
	 */
	public function getPagoAprobado()
	{
		return $this->pago_aprobado;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFecha($format = 'Y-m-d')
	{
		if ($this->fecha === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fecha);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [id_banco] column value.
	 * 
	 * @return     int
	 */
	public function getIdBanco()
	{
		return $this->id_banco;
	}

	/**
	 * Get the [numero_deposito] column value.
	 * 
	 * @return     int
	 */
	public function getNumeroDeposito()
	{
		return $this->numero_deposito;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_pago] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaPago($format = 'Y-m-d')
	{
		if ($this->fecha_pago === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fecha_pago);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_pago, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [es_pago_banco_nacional] column value.
	 * 
	 * @return     boolean
	 */
	public function getEsPagoBancoNacional()
	{
		return $this->es_pago_banco_nacional;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      string $v new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [monto] column.
	 * 
	 * @param      string $v new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setMonto($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->monto !== $v) {
			$this->monto = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::MONTO;
		}

		return $this;
	} // setMonto()

	/**
	 * Set the value of [id_feria] column.
	 * 
	 * @param      int $v new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setIdFeria($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_feria !== $v) {
			$this->id_feria = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::ID_FERIA;
		}

		if ($this->aFeria !== null && $this->aFeria->getId() !== $v) {
			$this->aFeria = null;
		}

		return $this;
	} // setIdFeria()

	/**
	 * Set the value of [id_expositor] column.
	 * 
	 * @param      int $v new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setIdExpositor($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_expositor !== $v) {
			$this->id_expositor = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::ID_EXPOSITOR;
		}

		if ($this->aExpositor !== null && $this->aExpositor->getId() !== $v) {
			$this->aExpositor = null;
		}

		return $this;
	} // setIdExpositor()

	/**
	 * Set the value of [id_usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setIdUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_usuario !== $v) {
			$this->id_usuario = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::ID_USUARIO;
		}

		if ($this->aUsuario !== null && $this->aUsuario->getId() !== $v) {
			$this->aUsuario = null;
		}

		return $this;
	} // setIdUsuario()

	/**
	 * Set the value of [id_expositor_feria] column.
	 * 
	 * @param      int $v new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setIdExpositorFeria($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_expositor_feria !== $v) {
			$this->id_expositor_feria = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::ID_EXPOSITOR_FERIA;
		}

		if ($this->aExpositorFeria !== null && $this->aExpositorFeria->getId() !== $v) {
			$this->aExpositorFeria = null;
		}

		return $this;
	} // setIdExpositorFeria()

	/**
	 * Sets the value of the [status_actual] column. 
	 * Non-boolean arguments are converted using the following rules:
	 *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
	 *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
	 * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
	 * 
	 * @param      boolean|integer|string $v The new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setStatusActual($v)
	{
		if ($v !== null) {
			if (is_string($v)) {
				$v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
			} else {
				$v = (boolean) $v;
			}
		}

		if ($this->status_actual !== $v) {
			$this->status_actual = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::STATUS_ACTUAL;
		}

		return $this;
	} // setStatusActual()

	/**
	 * Sets the value of the [pago_aprobado] column. 
	 * Non-boolean arguments are converted using the following rules:
	 *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
	 *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
	 * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
	 * 
	 * @param      boolean|integer|string $v The new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setPagoAprobado($v)
	{
		if ($v !== null) {
			if (is_string($v)) {
				$v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
			} else {
				$v = (boolean) $v;
			}
		}

		if ($this->pago_aprobado !== $v) {
			$this->pago_aprobado = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::PAGO_APROBADO;
		}

		return $this;
	} // setPagoAprobado()

	/**
	 * Sets the value of [fecha] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.
	 *               Empty strings are treated as NULL.
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setFecha($v)
	{
		$dt = PropelDateTime::newInstance($v, null, 'DateTime');
		if ($this->fecha !== null || $dt !== null) {
			$currentDateAsString = ($this->fecha !== null && $tmpDt = new DateTime($this->fecha)) ? $tmpDt->format('Y-m-d') : null;
			$newDateAsString = $dt ? $dt->format('Y-m-d') : null;
			if ($currentDateAsString !== $newDateAsString) {
				$this->fecha = $newDateAsString;
				$this->modifiedColumns[] = PagoExpositorPeer::FECHA;
			}
		} // if either are not null

		return $this;
	} // setFecha()

	/**
	 * Set the value of [id_banco] column.
	 * 
	 * @param      int $v new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setIdBanco($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_banco !== $v) {
			$this->id_banco = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::ID_BANCO;
		}

		if ($this->aBanco !== null && $this->aBanco->getId() !== $v) {
			$this->aBanco = null;
		}

		return $this;
	} // setIdBanco()

	/**
	 * Set the value of [numero_deposito] column.
	 * 
	 * @param      int $v new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setNumeroDeposito($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->numero_deposito !== $v) {
			$this->numero_deposito = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::NUMERO_DEPOSITO;
		}

		return $this;
	} // setNumeroDeposito()

	/**
	 * Sets the value of [fecha_pago] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.
	 *               Empty strings are treated as NULL.
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setFechaPago($v)
	{
		$dt = PropelDateTime::newInstance($v, null, 'DateTime');
		if ($this->fecha_pago !== null || $dt !== null) {
			$currentDateAsString = ($this->fecha_pago !== null && $tmpDt = new DateTime($this->fecha_pago)) ? $tmpDt->format('Y-m-d') : null;
			$newDateAsString = $dt ? $dt->format('Y-m-d') : null;
			if ($currentDateAsString !== $newDateAsString) {
				$this->fecha_pago = $newDateAsString;
				$this->modifiedColumns[] = PagoExpositorPeer::FECHA_PAGO;
			}
		} // if either are not null

		return $this;
	} // setFechaPago()

	/**
	 * Sets the value of the [es_pago_banco_nacional] column. 
	 * Non-boolean arguments are converted using the following rules:
	 *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
	 *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
	 * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
	 * 
	 * @param      boolean|integer|string $v The new value
	 * @return     PagoExpositor The current object (for fluent API support)
	 */
	public function setEsPagoBancoNacional($v)
	{
		if ($v !== null) {
			if (is_string($v)) {
				$v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
			} else {
				$v = (boolean) $v;
			}
		}

		if ($this->es_pago_banco_nacional !== $v) {
			$this->es_pago_banco_nacional = $v;
			$this->modifiedColumns[] = PagoExpositorPeer::ES_PAGO_BANCO_NACIONAL;
		}

		return $this;
	} // setEsPagoBancoNacional()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->monto = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->id_feria = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->id_expositor = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->id_usuario = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->id_expositor_feria = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->status_actual = ($row[$startcol + 6] !== null) ? (boolean) $row[$startcol + 6] : null;
			$this->pago_aprobado = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->fecha = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->id_banco = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->numero_deposito = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->fecha_pago = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->es_pago_banco_nacional = ($row[$startcol + 12] !== null) ? (boolean) $row[$startcol + 12] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 13; // 13 = PagoExpositorPeer::NUM_HYDRATE_COLUMNS.

		} catch (Exception $e) {
			throw new PropelException("Error populating PagoExpositor object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aFeria !== null && $this->id_feria !== $this->aFeria->getId()) {
			$this->aFeria = null;
		}
		if ($this->aExpositor !== null && $this->id_expositor !== $this->aExpositor->getId()) {
			$this->aExpositor = null;
		}
		if ($this->aUsuario !== null && $this->id_usuario !== $this->aUsuario->getId()) {
			$this->aUsuario = null;
		}
		if ($this->aExpositorFeria !== null && $this->id_expositor_feria !== $this->aExpositorFeria->getId()) {
			$this->aExpositorFeria = null;
		}
		if ($this->aBanco !== null && $this->id_banco !== $this->aBanco->getId()) {
			$this->aBanco = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PagoExpositorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PagoExpositorPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aFeria = null;
			$this->aExpositor = null;
			$this->aUsuario = null;
			$this->aExpositorFeria = null;
			$this->aBanco = null;
			$this->collStatuss = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PagoExpositorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePagoExpositor:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

			if ($ret) {
				PagoExpositorQuery::create()
					->filterByPrimaryKey($this->getPrimaryKey())
					->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePagoExpositor:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PagoExpositorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePagoExpositor:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePagoExpositor:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				PagoExpositorPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aFeria !== null) {
				if ($this->aFeria->isModified() || $this->aFeria->isNew()) {
					$affectedRows += $this->aFeria->save($con);
				}
				$this->setFeria($this->aFeria);
			}

			if ($this->aExpositor !== null) {
				if ($this->aExpositor->isModified() || $this->aExpositor->isNew()) {
					$affectedRows += $this->aExpositor->save($con);
				}
				$this->setExpositor($this->aExpositor);
			}

			if ($this->aUsuario !== null) {
				if ($this->aUsuario->isModified() || $this->aUsuario->isNew()) {
					$affectedRows += $this->aUsuario->save($con);
				}
				$this->setUsuario($this->aUsuario);
			}

			if ($this->aExpositorFeria !== null) {
				if ($this->aExpositorFeria->isModified() || $this->aExpositorFeria->isNew()) {
					$affectedRows += $this->aExpositorFeria->save($con);
				}
				$this->setExpositorFeria($this->aExpositorFeria);
			}

			if ($this->aBanco !== null) {
				if ($this->aBanco->isModified() || $this->aBanco->isNew()) {
					$affectedRows += $this->aBanco->save($con);
				}
				$this->setBanco($this->aBanco);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PagoExpositorPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$criteria = $this->buildCriteria();
					if ($criteria->keyContainsValue(PagoExpositorPeer::ID) ) {
						throw new PropelException('Cannot insert a value for auto-increment primary key ('.PagoExpositorPeer::ID.')');
					}

					$pk = BasePeer::doInsert($criteria, $con);
					$affectedRows += 1;
					$this->setId($pk);  //[IMV] update autoincrement primary key
					$this->setNew(false);
				} else {
					$affectedRows += PagoExpositorPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collStatuss !== null) {
				foreach ($this->collStatuss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aFeria !== null) {
				if (!$this->aFeria->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aFeria->getValidationFailures());
				}
			}

			if ($this->aExpositor !== null) {
				if (!$this->aExpositor->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aExpositor->getValidationFailures());
				}
			}

			if ($this->aUsuario !== null) {
				if (!$this->aUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuario->getValidationFailures());
				}
			}

			if ($this->aExpositorFeria !== null) {
				if (!$this->aExpositorFeria->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aExpositorFeria->getValidationFailures());
				}
			}

			if ($this->aBanco !== null) {
				if (!$this->aBanco->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aBanco->getValidationFailures());
				}
			}


			if (($retval = PagoExpositorPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collStatuss !== null) {
					foreach ($this->collStatuss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PagoExpositorPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getMonto();
				break;
			case 2:
				return $this->getIdFeria();
				break;
			case 3:
				return $this->getIdExpositor();
				break;
			case 4:
				return $this->getIdUsuario();
				break;
			case 5:
				return $this->getIdExpositorFeria();
				break;
			case 6:
				return $this->getStatusActual();
				break;
			case 7:
				return $this->getPagoAprobado();
				break;
			case 8:
				return $this->getFecha();
				break;
			case 9:
				return $this->getIdBanco();
				break;
			case 10:
				return $this->getNumeroDeposito();
				break;
			case 11:
				return $this->getFechaPago();
				break;
			case 12:
				return $this->getEsPagoBancoNacional();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
	{
		if (isset($alreadyDumpedObjects['PagoExpositor'][$this->getPrimaryKey()])) {
			return '*RECURSION*';
		}
		$alreadyDumpedObjects['PagoExpositor'][$this->getPrimaryKey()] = true;
		$keys = PagoExpositorPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getMonto(),
			$keys[2] => $this->getIdFeria(),
			$keys[3] => $this->getIdExpositor(),
			$keys[4] => $this->getIdUsuario(),
			$keys[5] => $this->getIdExpositorFeria(),
			$keys[6] => $this->getStatusActual(),
			$keys[7] => $this->getPagoAprobado(),
			$keys[8] => $this->getFecha(),
			$keys[9] => $this->getIdBanco(),
			$keys[10] => $this->getNumeroDeposito(),
			$keys[11] => $this->getFechaPago(),
			$keys[12] => $this->getEsPagoBancoNacional(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->aFeria) {
				$result['Feria'] = $this->aFeria->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->aExpositor) {
				$result['Expositor'] = $this->aExpositor->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->aUsuario) {
				$result['Usuario'] = $this->aUsuario->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->aExpositorFeria) {
				$result['ExpositorFeria'] = $this->aExpositorFeria->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->aBanco) {
				$result['Banco'] = $this->aBanco->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->collStatuss) {
				$result['Statuss'] = $this->collStatuss->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PagoExpositorPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setMonto($value);
				break;
			case 2:
				$this->setIdFeria($value);
				break;
			case 3:
				$this->setIdExpositor($value);
				break;
			case 4:
				$this->setIdUsuario($value);
				break;
			case 5:
				$this->setIdExpositorFeria($value);
				break;
			case 6:
				$this->setStatusActual($value);
				break;
			case 7:
				$this->setPagoAprobado($value);
				break;
			case 8:
				$this->setFecha($value);
				break;
			case 9:
				$this->setIdBanco($value);
				break;
			case 10:
				$this->setNumeroDeposito($value);
				break;
			case 11:
				$this->setFechaPago($value);
				break;
			case 12:
				$this->setEsPagoBancoNacional($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PagoExpositorPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setMonto($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdFeria($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setIdExpositor($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setIdUsuario($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setIdExpositorFeria($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setStatusActual($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPagoAprobado($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFecha($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setIdBanco($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setNumeroDeposito($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setFechaPago($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setEsPagoBancoNacional($arr[$keys[12]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PagoExpositorPeer::DATABASE_NAME);

		if ($this->isColumnModified(PagoExpositorPeer::ID)) $criteria->add(PagoExpositorPeer::ID, $this->id);
		if ($this->isColumnModified(PagoExpositorPeer::MONTO)) $criteria->add(PagoExpositorPeer::MONTO, $this->monto);
		if ($this->isColumnModified(PagoExpositorPeer::ID_FERIA)) $criteria->add(PagoExpositorPeer::ID_FERIA, $this->id_feria);
		if ($this->isColumnModified(PagoExpositorPeer::ID_EXPOSITOR)) $criteria->add(PagoExpositorPeer::ID_EXPOSITOR, $this->id_expositor);
		if ($this->isColumnModified(PagoExpositorPeer::ID_USUARIO)) $criteria->add(PagoExpositorPeer::ID_USUARIO, $this->id_usuario);
		if ($this->isColumnModified(PagoExpositorPeer::ID_EXPOSITOR_FERIA)) $criteria->add(PagoExpositorPeer::ID_EXPOSITOR_FERIA, $this->id_expositor_feria);
		if ($this->isColumnModified(PagoExpositorPeer::STATUS_ACTUAL)) $criteria->add(PagoExpositorPeer::STATUS_ACTUAL, $this->status_actual);
		if ($this->isColumnModified(PagoExpositorPeer::PAGO_APROBADO)) $criteria->add(PagoExpositorPeer::PAGO_APROBADO, $this->pago_aprobado);
		if ($this->isColumnModified(PagoExpositorPeer::FECHA)) $criteria->add(PagoExpositorPeer::FECHA, $this->fecha);
		if ($this->isColumnModified(PagoExpositorPeer::ID_BANCO)) $criteria->add(PagoExpositorPeer::ID_BANCO, $this->id_banco);
		if ($this->isColumnModified(PagoExpositorPeer::NUMERO_DEPOSITO)) $criteria->add(PagoExpositorPeer::NUMERO_DEPOSITO, $this->numero_deposito);
		if ($this->isColumnModified(PagoExpositorPeer::FECHA_PAGO)) $criteria->add(PagoExpositorPeer::FECHA_PAGO, $this->fecha_pago);
		if ($this->isColumnModified(PagoExpositorPeer::ES_PAGO_BANCO_NACIONAL)) $criteria->add(PagoExpositorPeer::ES_PAGO_BANCO_NACIONAL, $this->es_pago_banco_nacional);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PagoExpositorPeer::DATABASE_NAME);
		$criteria->add(PagoExpositorPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of PagoExpositor (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @param      boolean $makeNew Whether to reset autoincrement PKs and make the object new.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
	{
		$copyObj->setMonto($this->getMonto());
		$copyObj->setIdFeria($this->getIdFeria());
		$copyObj->setIdExpositor($this->getIdExpositor());
		$copyObj->setIdUsuario($this->getIdUsuario());
		$copyObj->setIdExpositorFeria($this->getIdExpositorFeria());
		$copyObj->setStatusActual($this->getStatusActual());
		$copyObj->setPagoAprobado($this->getPagoAprobado());
		$copyObj->setFecha($this->getFecha());
		$copyObj->setIdBanco($this->getIdBanco());
		$copyObj->setNumeroDeposito($this->getNumeroDeposito());
		$copyObj->setFechaPago($this->getFechaPago());
		$copyObj->setEsPagoBancoNacional($this->getEsPagoBancoNacional());

		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getStatuss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addStatus($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)

		if ($makeNew) {
			$copyObj->setNew(true);
			$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
		}
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     PagoExpositor Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PagoExpositorPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PagoExpositorPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Feria object.
	 *
	 * @param      Feria $v
	 * @return     PagoExpositor The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setFeria(Feria $v = null)
	{
		if ($v === null) {
			$this->setIdFeria(NULL);
		} else {
			$this->setIdFeria($v->getId());
		}

		$this->aFeria = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Feria object, it will not be re-added.
		if ($v !== null) {
			$v->addPagoExpositor($this);
		}

		return $this;
	}


	/**
	 * Get the associated Feria object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Feria The associated Feria object.
	 * @throws     PropelException
	 */
	public function getFeria(PropelPDO $con = null)
	{
		if ($this->aFeria === null && ($this->id_feria !== null)) {
			$this->aFeria = FeriaQuery::create()->findPk($this->id_feria, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aFeria->addPagoExpositors($this);
			 */
		}
		return $this->aFeria;
	}

	/**
	 * Declares an association between this object and a Expositor object.
	 *
	 * @param      Expositor $v
	 * @return     PagoExpositor The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setExpositor(Expositor $v = null)
	{
		if ($v === null) {
			$this->setIdExpositor(NULL);
		} else {
			$this->setIdExpositor($v->getId());
		}

		$this->aExpositor = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Expositor object, it will not be re-added.
		if ($v !== null) {
			$v->addPagoExpositor($this);
		}

		return $this;
	}


	/**
	 * Get the associated Expositor object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Expositor The associated Expositor object.
	 * @throws     PropelException
	 */
	public function getExpositor(PropelPDO $con = null)
	{
		if ($this->aExpositor === null && ($this->id_expositor !== null)) {
			$this->aExpositor = ExpositorQuery::create()->findPk($this->id_expositor, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aExpositor->addPagoExpositors($this);
			 */
		}
		return $this->aExpositor;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     PagoExpositor The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuario(Usuario $v = null)
	{
		if ($v === null) {
			$this->setIdUsuario(NULL);
		} else {
			$this->setIdUsuario($v->getId());
		}

		$this->aUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addPagoExpositor($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuario(PropelPDO $con = null)
	{
		if ($this->aUsuario === null && ($this->id_usuario !== null)) {
			$this->aUsuario = UsuarioQuery::create()->findPk($this->id_usuario, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aUsuario->addPagoExpositors($this);
			 */
		}
		return $this->aUsuario;
	}

	/**
	 * Declares an association between this object and a ExpositorFeria object.
	 *
	 * @param      ExpositorFeria $v
	 * @return     PagoExpositor The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setExpositorFeria(ExpositorFeria $v = null)
	{
		if ($v === null) {
			$this->setIdExpositorFeria(NULL);
		} else {
			$this->setIdExpositorFeria($v->getId());
		}

		$this->aExpositorFeria = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ExpositorFeria object, it will not be re-added.
		if ($v !== null) {
			$v->addPagoExpositor($this);
		}

		return $this;
	}


	/**
	 * Get the associated ExpositorFeria object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ExpositorFeria The associated ExpositorFeria object.
	 * @throws     PropelException
	 */
	public function getExpositorFeria(PropelPDO $con = null)
	{
		if ($this->aExpositorFeria === null && ($this->id_expositor_feria !== null)) {
			$this->aExpositorFeria = ExpositorFeriaQuery::create()->findPk($this->id_expositor_feria, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aExpositorFeria->addPagoExpositors($this);
			 */
		}
		return $this->aExpositorFeria;
	}

	/**
	 * Declares an association between this object and a Banco object.
	 *
	 * @param      Banco $v
	 * @return     PagoExpositor The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setBanco(Banco $v = null)
	{
		if ($v === null) {
			$this->setIdBanco(NULL);
		} else {
			$this->setIdBanco($v->getId());
		}

		$this->aBanco = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Banco object, it will not be re-added.
		if ($v !== null) {
			$v->addPagoExpositor($this);
		}

		return $this;
	}


	/**
	 * Get the associated Banco object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Banco The associated Banco object.
	 * @throws     PropelException
	 */
	public function getBanco(PropelPDO $con = null)
	{
		if ($this->aBanco === null && ($this->id_banco !== null)) {
			$this->aBanco = BancoQuery::create()->findPk($this->id_banco, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aBanco->addPagoExpositors($this);
			 */
		}
		return $this->aBanco;
	}


	/**
	 * Initializes a collection based on the name of a relation.
	 * Avoids crafting an 'init[$relationName]s' method name 
	 * that wouldn't work when StandardEnglishPluralizer is used.
	 *
	 * @param      string $relationName The name of the relation to initialize
	 * @return     void
	 */
	public function initRelation($relationName)
	{
		if ('Status' == $relationName) {
			return $this->initStatuss();
		}
	}

	/**
	 * Clears out the collStatuss collection
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addStatuss()
	 */
	public function clearStatuss()
	{
		$this->collStatuss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collStatuss collection.
	 *
	 * By default this just sets the collStatuss collection to an empty array (like clearcollStatuss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @param      boolean $overrideExisting If set to true, the method call initializes
	 *                                        the collection even if it is not empty
	 *
	 * @return     void
	 */
	public function initStatuss($overrideExisting = true)
	{
		if (null !== $this->collStatuss && !$overrideExisting) {
			return;
		}
		$this->collStatuss = new PropelObjectCollection();
		$this->collStatuss->setModel('Status');
	}

	/**
	 * Gets an array of Status objects which contain a foreign key that references this object.
	 *
	 * If the $criteria is not null, it is used to always fetch the results from the database.
	 * Otherwise the results are fetched from the database the first time, then cached.
	 * Next time the same method is called without $criteria, the cached collection is returned.
	 * If this PagoExpositor is new, it will return
	 * an empty collection or the current collection; the criteria is ignored on a new object.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @return     PropelCollection|array Status[] List of Status objects
	 * @throws     PropelException
	 */
	public function getStatuss($criteria = null, PropelPDO $con = null)
	{
		if(null === $this->collStatuss || null !== $criteria) {
			if ($this->isNew() && null === $this->collStatuss) {
				// return empty collection
				$this->initStatuss();
			} else {
				$collStatuss = StatusQuery::create(null, $criteria)
					->filterByPagoExpositor($this)
					->find($con);
				if (null !== $criteria) {
					return $collStatuss;
				}
				$this->collStatuss = $collStatuss;
			}
		}
		return $this->collStatuss;
	}

	/**
	 * Returns the number of related Status objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Status objects.
	 * @throws     PropelException
	 */
	public function countStatuss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if(null === $this->collStatuss || null !== $criteria) {
			if ($this->isNew() && null === $this->collStatuss) {
				return 0;
			} else {
				$query = StatusQuery::create(null, $criteria);
				if($distinct) {
					$query->distinct();
				}
				return $query
					->filterByPagoExpositor($this)
					->count($con);
			}
		} else {
			return count($this->collStatuss);
		}
	}

	/**
	 * Method called to associate a Status object to this object
	 * through the Status foreign key attribute.
	 *
	 * @param      Status $l Status
	 * @return     void
	 * @throws     PropelException
	 */
	public function addStatus(Status $l)
	{
		if ($this->collStatuss === null) {
			$this->initStatuss();
		}
		if (!$this->collStatuss->contains($l)) { // only add it if the **same** object is not already associated
			$this->collStatuss[]= $l;
			$l->setPagoExpositor($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this PagoExpositor is new, it will return
	 * an empty collection; or if this PagoExpositor has previously
	 * been saved, it will retrieve related Statuss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in PagoExpositor.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
	 * @return     PropelCollection|array Status[] List of Status objects
	 */
	public function getStatussJoinFeria($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$query = StatusQuery::create(null, $criteria);
		$query->joinWith('Feria', $join_behavior);

		return $this->getStatuss($query, $con);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this PagoExpositor is new, it will return
	 * an empty collection; or if this PagoExpositor has previously
	 * been saved, it will retrieve related Statuss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in PagoExpositor.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
	 * @return     PropelCollection|array Status[] List of Status objects
	 */
	public function getStatussJoinExpositor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$query = StatusQuery::create(null, $criteria);
		$query->joinWith('Expositor', $join_behavior);

		return $this->getStatuss($query, $con);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this PagoExpositor is new, it will return
	 * an empty collection; or if this PagoExpositor has previously
	 * been saved, it will retrieve related Statuss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in PagoExpositor.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
	 * @return     PropelCollection|array Status[] List of Status objects
	 */
	public function getStatussJoinTipoStatus($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$query = StatusQuery::create(null, $criteria);
		$query->joinWith('TipoStatus', $join_behavior);

		return $this->getStatuss($query, $con);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this PagoExpositor is new, it will return
	 * an empty collection; or if this PagoExpositor has previously
	 * been saved, it will retrieve related Statuss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in PagoExpositor.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
	 * @return     PropelCollection|array Status[] List of Status objects
	 */
	public function getStatussJoinExpositorFeria($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$query = StatusQuery::create(null, $criteria);
		$query->joinWith('ExpositorFeria', $join_behavior);

		return $this->getStatuss($query, $con);
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->monto = null;
		$this->id_feria = null;
		$this->id_expositor = null;
		$this->id_usuario = null;
		$this->id_expositor_feria = null;
		$this->status_actual = null;
		$this->pago_aprobado = null;
		$this->fecha = null;
		$this->id_banco = null;
		$this->numero_deposito = null;
		$this->fecha_pago = null;
		$this->es_pago_banco_nacional = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->applyDefaultValues();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all references to other model objects or collections of model objects.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect
	 * objects with circular references (even in PHP 5.3). This is currently necessary
	 * when using Propel in certain daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all referrer objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collStatuss) {
				foreach ($this->collStatuss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		if ($this->collStatuss instanceof PropelCollection) {
			$this->collStatuss->clearIterator();
		}
		$this->collStatuss = null;
		$this->aFeria = null;
		$this->aExpositor = null;
		$this->aUsuario = null;
		$this->aExpositorFeria = null;
		$this->aBanco = null;
	}

	/**
	 * Return the string representation of this object
	 *
	 * @return string
	 */
	public function __toString()
	{
		return (string) $this->exportTo(PagoExpositorPeer::DEFAULT_STRING_FORMAT);
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BasePagoExpositor:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}

		if (preg_match('/get(\w+)/', $name, $matches)) {
			$virtualColumn = $matches[1];
			if ($this->hasVirtualColumn($virtualColumn)) {
				return $this->getVirtualColumn($virtualColumn);
			}
			// no lcfirst in php<5.3...
			$virtualColumn[0] = strtolower($virtualColumn[0]);
			if ($this->hasVirtualColumn($virtualColumn)) {
				return $this->getVirtualColumn($virtualColumn);
			}
		}
		return parent::__call($name, $params);
	}

} // BasePagoExpositor
