<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/02/22 12:26:33

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'pgsql:host=localhost;dbname=r',
  'username' => 'postgres',
  'password' => 'postgres',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
