<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/01/25 11:24:13
sfConfig::add(array(
  'mod_pago_expositor_enabled' => true,
  'mod_pago_expositor_view_class' => 'sfPHP',
));
