/*
 * Globalize Culture es-VE
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
    typeof exports !== "undefined" &&
    typeof module !== "undefined" ) {
    // Assume CommonJS
    Globalize = require( "globalize" );
} else {
    // Global variable
    Globalize = window.Globalize;
}

Globalize.calendars = {};
Globalize.calendars.days = {
                names: ["domingo","lunes","martes","miércoles","jueves","viernes","sábado"],
                namesAbbr: ["dom","lun","mar","mié","jue","vie","sáb"],
                namesShort: ["do","lu","ma","mi","ju","vi","sá"]
           };

Globalize.calendars.months = {
    names: ["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre",""],
    namesAbbr: ["ene","feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic",""]
};

Globalize.calendars.AM = ["a.m.","a.m.","A.M."];
Globalize.calendars.PM = ["p.m.","p.m.","P.M."];
Globalize.calendars.eras = [{"name":"d.C.","start":null,"offset":0}];
Globalize.calendars.patterns = {
    d: "dd/MM/yyyy",
    D: "yyyy-MM-dd hh:mm:ss",
    t: "hh:mm tt",
    T: "hh:mm:ss tt",
    f : "dddd, MMMM dd, yyyy h:mm tt",
    F : "dddd, MMMM dd, yyyy h:mm:ss tt",
    M: "dd MMMM",
    Y: "MMMM' de 'yyyy",
    S : "yyyy\u0027-\u0027MM\u0027-\u0027dd\u0027T\u0027HH\u0027:\u0027mm\u0027:\u0027ss",
    ISO : "yyyy-MM-dd hh:mm:ss",
    ISO2 : "yyyy-MM-dd HH:mm:ss",
    d1 : "dd.MM.yyyy",
    d2 : "dd-MM-yyyy",
    d3 : "dd-MMMM-yyyy",
    d4 : "dd-MM-yy",
    d5 : "H:mm",
    d6 : "HH:mm",
    d7 : "HH:mm tt",
    d8 : "dd/MMMM/yyyy",
    d9 : "MMMM-dd",
    d10 : "MM-dd",
    d11 : "MM-dd-yyyy"
};

Globalize.addCultureInfo( "es-VE", "default", {
    name: "es-VE",
    englishName: "Spanish (Bolivarian Republic of Venezuela)",
    nativeName: "Español (República Bolivariana de Venezuela)",
    language: "es",
    numberFormat: {
        ",": ".",
        ".": ",",
        "NaN": "NaN",
        negativeInfinity: "-Infinito",
        positiveInfinity: "Infinito",
        percent: {
            ",": ".",
            ".": ","
        },
        currency: {
            pattern: ["$ -n","$ n"],
            ",": ".",
            ".": ",",
            symbol: "Bs. F."
        }
    },
    days: Globalize.calendars.days,
    months: Globalize.calendars.months,
    AM: Globalize.calendars.AM,
    PM: Globalize.calendars.PM,
    eras: Globalize.calendars.eras,
    patterns: Globalize.calendars.patterns, 
    
    calendars: {
        standard: {
            days: Globalize.calendars.days,
            months: Globalize.calendars.months,
            AM: Globalize.calendars.AM,
            PM: Globalize.calendars.PM,
            eras: Globalize.calendars.eras,
            patterns: Globalize.calendars.patterns
        }
    },
    pagergotopagestring : "Ir a la página:",
    pagershowrowsstring : "Filas mostradas:",
    pagerrangestring : " de ",
    pagernextbuttonstring : "Siguiente",
    pagerpreviousbuttonstring : "Anterior",
    sortascendingstring : "Ordenar ascendentemente",
    sortdescendingstring : "Ordenar descendentemente",
    sortremovestring : "Remover ordenamiento",
    filterstring : "Filtrar",
    filtershowrowstring : "Mostrar filas aquí:",
    filterorconditionstring : "O",
    filterandconditionstring : "Y",
    filterdatecomparisonoperators : 
    [
        'Igual', 'Distinto', 'Menor que', 'Menor o igual que', 
        'Mayor que', 'Mayor o igual que', 'Nulo', 'No nulo'
    ],
    filterstringcomparisonoperators : 
    [
        'Vacio', 'No Vacio', 'Contiene', 'Contiene(match case)',
        'No contiene', 'No contiene(match case)', 'Empieza con', 
        'Empieza con(match case)','Termina con', 'Termina con(match case)', 
        'Igual', 'Igual(match case)', 'Nulo', 'No nulo'
    ],
    filternumericcomparisonoperators : 
    [
        'Igual', 'Distinto', 'Menor que', 'Menor o igual que', 
        'Mayor que', 'Mayor o igual que', 'Nulo', 'No Nulo'
    ],
    filterselectallstring : "(Seleccionar todo)",
    filterselectstring: "Seleccione filtro",
    filterchoosestring : "Seleccione:", 
    filterbooleancomparisonoperators : ['Igual', 'Distinto'],
    validationstring : "El valor que introdujo no es válido",
    emptydatastring : "No hay datos para mostrar",
    groupsheaderstring : "Arrastre una columna y suéltela aquí para agrupar por esa columna",
    groupbystring : "Agrupar por esta columna",
    groupremovestring : "Eliminar del grupo",
    filterclearstring : "Limpiar",
    todaystring : "Hoy",
    clearstring : "Limpiar",
    loadtext: "Cargando..."
});

}( this ));