<?php



/**
 * Skeleton subclass for representing a row from the 'incumplmiento_actividad_finalizada' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.2-dev on:
 *
 * Sat Feb 14 19:21:57 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class IncumplmientoActividadFinalizada extends BaseIncumplmientoActividadFinalizada {

} // IncumplmientoActividadFinalizada
