<?php



/**
 * Skeleton subclass for performing query and update operations on the 'linea_editorial' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.2-dev on:
 *
 * Sat Oct  4 11:31:36 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class LineaEditorialQuery extends BaseLineaEditorialQuery {

} // LineaEditorialQuery
