<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/12/25 22:50:06
sfConfig::add(array(
  'mod_pago_expositor_enabled' => true,
  'mod_pago_expositor_view_class' => 'sfPHP',
));
